"""2-tier multi-agent cascade analysis on OOD distributions.

Mirrors `make_cascade_2tier.py` (TriviaQA ID) but uses:
  - Qwen-7B sample0 strict_correct from `runs/qwen7b/<dataset>_ood.npz`
  - GPT-OSS-120B greedy strict_correct + per-question latency from
    `runs/teacher_oss120b_<dataset>.jsonl` (generated by run_teacher_on_ood.py)
  - Probe scores (DCP-MLP, SEPs-LR, SEPs-Ridge) from
    `results/per_item_predictions_all.csv` filtered by
    base="qwen7b", dataset in {"hotpotqa","nq"}.

Cost units: Qwen-7B K=1 = 1.0; teacher cost = actual median GPT-OSS latency
(measured per OOD dataset) divided by Qwen-7B latency.

Outputs (per dataset):
  results/cascade_2tier_<dataset>_results.csv
  results/cascade_2tier_<dataset>_savings.csv
  reports/dashboard_cascade_2tier_<dataset>.png
And a combined report:
  results/cascade_2tier_ood_summary.csv
  reports/dashboard_cascade_2tier_ood.png   (3-row layout: ID + 2 OOD)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpec

THIS_DIR = Path(__file__).resolve().parents[1]

# Real measured latencies (ms) on H200, fp16 / bfloat16
QWEN_LATENCY_MS = 324                  # measured greedy on Qwen2.5-7B
DEFAULT_TEACHER_LATENCY_MS = 4562      # ID median; we override per OOD using actual

PROBE_NAMES = ["DCP_mlp", "SEPs_logreg", "SEPs_ridge"]
PROBE_PRETTY = {
    "DCP_mlp": "DCP-MLP (ours)",
    "SEPs_logreg": "SEPs-LR",
    "SEPs_ridge": "SEPs-Ridge (Kossen 2024)",
}
PROBE_COLORS = {
    "DCP_mlp": "#d62728",
    "SEPs_logreg": "#1f77b4",
    "SEPs_ridge": "#7f7f7f",
}
PROBE_MARKERS = {
    "DCP_mlp": "o", "SEPs_logreg": "s", "SEPs_ridge": "D",
}
DATASET_PRETTY = {
    "id": "TriviaQA (ID)",
    "hotpotqa": "HotpotQA dev_distractor (OOD)",
    "nq": "NQ-Open validation (OOD)",
}


# ---------------------------------------------------------------------------
# Build aligned per-question table
# ---------------------------------------------------------------------------


def build_aligned_table(dataset: str) -> tuple[pd.DataFrame, dict]:
    """Return (table, meta) for the given OOD dataset name in {hotpotqa, nq}."""
    # 1) Qwen-7B sample0 strict_correct from OOD npz
    npz = np.load(THIS_DIR / "runs" / "qwen7b" / f"{dataset}_ood.npz",
                  allow_pickle=True)
    qids = list(npz["question_ids"])
    q_correct = list(npz["strict_correct"])
    qwen_per_q = pd.DataFrame({
        "question_id": qids,
        "qwen_sample0_correct": [float(c) for c in q_correct],
    })

    # 2) Teacher correctness + latency from JSONL
    t_path = THIS_DIR / "runs" / f"teacher_oss120b_{dataset}.jsonl"
    teacher_records = []
    with open(t_path) as f:
        for line in f:
            r = json.loads(line)
            if r.get("missing"):
                continue
            teacher_records.append({
                "question_id": r["question_id"],
                "teacher_greedy_correct": float(r.get("teacher_strict_correct", 0)),
                "teacher_latency_ms": float(r.get("latency_ms", 0)),
                "teacher_completion_tokens": int(r.get("completion_tokens", 0)),
            })
    teacher_per_q = pd.DataFrame(teacher_records)

    # 3) Probe scores from per_item_predictions_all.csv
    pred = pd.read_csv(THIS_DIR / "results" / "per_item_predictions_all.csv")
    pred = pred[(pred["base"] == "qwen7b") & (pred["dataset"] == dataset)]

    table = qwen_per_q.merge(teacher_per_q, on="question_id", how="inner")
    for probe in PROBE_NAMES:
        psub = pred[pred["probe"] == probe][["question_id", "y_score"]]
        psub = psub.rename(columns={"y_score": f"score_{probe}"})
        table = table.merge(psub, on="question_id", how="left")

    n_dropped = len(qwen_per_q) + len(teacher_per_q) - 2 * len(table)
    teacher_lat_med = (table["teacher_latency_ms"].median()
                       if "teacher_latency_ms" in table else DEFAULT_TEACHER_LATENCY_MS)
    meta = {
        "dataset": dataset,
        "n_aligned": len(table),
        "n_dropped_misalign": n_dropped,
        "qwen_acc": float(table["qwen_sample0_correct"].mean()),
        "teacher_acc": float(table["teacher_greedy_correct"].mean()),
        "teacher_latency_ms_median": float(teacher_lat_med),
        "teacher_latency_ms_p90": float(table["teacher_latency_ms"].quantile(0.9)),
        "teacher_completion_tokens_median": float(table["teacher_completion_tokens"].median()),
        "cost_ratio_teacher_over_qwen": float(teacher_lat_med / QWEN_LATENCY_MS),
    }
    return table, meta


# ---------------------------------------------------------------------------
# Cascade simulation (percentile-based escalation)
# ---------------------------------------------------------------------------


def simulate_cascade(table: pd.DataFrame, probe: str, escalation_rate: float,
                     cost_teacher: float) -> tuple[float, float, float, float]:
    score = table[f"score_{probe}"].to_numpy()
    qwen_correct = table["qwen_sample0_correct"].to_numpy()
    teacher_correct = table["teacher_greedy_correct"].to_numpy()
    if escalation_rate <= 0:
        threshold = float(np.min(score)) - 1.0
        commit_qwen = np.ones(len(score), dtype=bool)
    elif escalation_rate >= 1:
        threshold = float(np.max(score)) + 1.0
        commit_qwen = np.zeros(len(score), dtype=bool)
    else:
        threshold = float(np.quantile(score, escalation_rate))
        commit_qwen = score > threshold
    correct = np.where(commit_qwen, qwen_correct, teacher_correct)
    cost = np.where(commit_qwen, 1.0, 1.0 + cost_teacher)
    actual_frac = float((~commit_qwen).mean())
    return float(cost.mean()), float(correct.mean()), actual_frac, threshold


def simulate_random(table: pd.DataFrame, p_keep: float, cost_teacher: float,
                    n_trials: int = 50, seed: int = 0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    qc = table["qwen_sample0_correct"].to_numpy()
    tc = table["teacher_greedy_correct"].to_numpy()
    costs, accs = [], []
    for _ in range(n_trials):
        commit_qwen = rng.random(len(table)) < p_keep
        correct = np.where(commit_qwen, qc, tc)
        cost = np.where(commit_qwen, 1.0, 1.0 + cost_teacher)
        costs.append(cost.mean()); accs.append(correct.mean())
    return float(np.mean(costs)), float(np.mean(accs))


def simulate_oracle(table: pd.DataFrame, cost_teacher: float) -> tuple[float, float, float]:
    qc = table["qwen_sample0_correct"].to_numpy()
    tc = table["teacher_greedy_correct"].to_numpy()
    commit_qwen = qc > 0.5
    correct = np.where(commit_qwen, qc, tc)
    cost = np.where(commit_qwen, 1.0, 1.0 + cost_teacher)
    return float(cost.mean()), float(correct.mean()), float((~commit_qwen).mean())


def sweep_all_strategies(table: pd.DataFrame, cost_teacher: float) -> pd.DataFrame:
    rows = []
    qa = float(table["qwen_sample0_correct"].mean())
    ta = float(table["teacher_greedy_correct"].mean())
    rows.append({"strategy": "always_qwen", "probe": None, "threshold": np.nan,
                 "cost": 1.0, "accuracy": qa, "frac_escalated": 0.0})
    rows.append({"strategy": "always_teacher", "probe": None, "threshold": np.nan,
                 "cost": cost_teacher, "accuracy": ta, "frac_escalated": 1.0})
    rates = np.linspace(0.0, 1.0, 101)
    for probe in PROBE_NAMES:
        for r in rates:
            cost, acc, actual_frac, th = simulate_cascade(table, probe, r, cost_teacher)
            rows.append({"strategy": "probe_cascade", "probe": probe,
                         "threshold": th, "cost": cost, "accuracy": acc,
                         "frac_escalated": actual_frac, "target_escalation_rate": r})
    for p in np.linspace(0.0, 1.0, 41):
        cost, acc = simulate_random(table, p, cost_teacher)
        rows.append({"strategy": "random_cascade", "probe": None,
                     "threshold": p, "cost": cost, "accuracy": acc,
                     "frac_escalated": 1.0 - p})
    cost, acc, fe = simulate_oracle(table, cost_teacher)
    rows.append({"strategy": "oracle_cascade", "probe": None, "threshold": np.nan,
                 "cost": cost, "accuracy": acc, "frac_escalated": fe})
    return pd.DataFrame(rows)


def cost_savings_at_acc(df: pd.DataFrame, targets: list[float],
                        cost_teacher: float) -> pd.DataFrame:
    rows = []
    for tgt in targets:
        always_q = df[df["strategy"] == "always_qwen"].iloc[0]
        always_t = df[df["strategy"] == "always_teacher"].iloc[0]
        for probe in PROBE_NAMES:
            sub = df[(df["strategy"] == "probe_cascade") & (df["probe"] == probe)]
            meet = sub[sub["accuracy"] >= tgt].sort_values("cost")
            if meet.empty:
                cheapest = "—"
                savings = "—"
            else:
                r = meet.iloc[0]
                cheapest = f"{r['cost']:.2f} (esc={r['frac_escalated']:.0%})"
                savings = f"{(always_t['cost'] - r['cost']) / always_t['cost'] * 100:+.0f}%"
            rows.append({"target_acc": tgt,
                         "probe": PROBE_PRETTY[probe],
                         "cheapest_cost": cheapest,
                         "savings_vs_always_teacher": savings,
                         "always_qwen_meets": "✓" if always_q["accuracy"] >= tgt else "✗"})
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------


def panel_pareto(ax, df: pd.DataFrame, table: pd.DataFrame, meta: dict) -> None:
    aq = df[df["strategy"] == "always_qwen"].iloc[0]
    at = df[df["strategy"] == "always_teacher"].iloc[0]
    ax.scatter(aq["cost"], aq["accuracy"], s=160, marker="s", color="#3182bd",
               edgecolors="black", linewidths=0.7, zorder=4)
    ax.annotate("Always Qwen-7B", (aq["cost"], aq["accuracy"]),
                textcoords="offset points", xytext=(8, -16), fontsize=8.5,
                color="#3182bd")
    ax.scatter(at["cost"], at["accuracy"], s=180, marker="*", color="#000000",
               edgecolors="black", linewidths=0.7, zorder=4)
    ax.annotate("Always GPT-OSS-120B", (at["cost"], at["accuracy"]),
                textcoords="offset points", xytext=(-110, -3), fontsize=8.5)

    rc = df[df["strategy"] == "random_cascade"].sort_values("cost")
    ax.plot(rc["cost"], rc["accuracy"], color="#bcbcbc", linewidth=1.0,
            marker="x", markersize=3.5, alpha=0.6,
            label="Random cascade", zorder=2)
    for probe in PROBE_NAMES:
        sub = df[(df["strategy"] == "probe_cascade") & (df["probe"] == probe)]
        sub = sub.sort_values("cost")
        ax.plot(sub["cost"], sub["accuracy"],
                color=PROBE_COLORS[probe], marker=PROBE_MARKERS[probe],
                markersize=3.5, linewidth=1.6, alpha=0.95,
                label=f"{PROBE_PRETTY[probe]}", zorder=5)
    oc = df[df["strategy"] == "oracle_cascade"]
    if not oc.empty:
        r = oc.iloc[0]
        ax.scatter(r["cost"], r["accuracy"], s=180, marker="v",
                   color="#2ca02c", edgecolors="black", linewidths=0.8, zorder=6)
        ax.annotate(f"Oracle\n(cost={r['cost']:.2f}, acc={r['accuracy']:.2f})",
                    (r["cost"], r["accuracy"]),
                    textcoords="offset points", xytext=(-10, -36), fontsize=8,
                    color="#2ca02c")
    ax.set_xlabel("Avg cost / question (Qwen-7B forward units)")
    ax.set_ylabel("Avg accuracy")
    ax.set_xscale("log")
    ax.set_title(
        f"{DATASET_PRETTY[meta['dataset']]} — n={meta['n_aligned']} | "
        f"Qwen={meta['qwen_acc']:.3f}  GPT-OSS={meta['teacher_acc']:.3f}  "
        f"cost ratio={meta['cost_ratio_teacher_over_qwen']:.1f}x",
        fontsize=10,
    )
    ax.grid(linestyle=":", alpha=0.4)
    ax.legend(loc="lower right", fontsize=8.0, framealpha=0.95)
    ymin = max(0.0, min(aq["accuracy"], at["accuracy"]) - 0.05)
    ymax = min(1.0, max(at["accuracy"], aq["accuracy"]) + 0.10)
    ax.set_ylim(ymin, ymax)


def panel_acc_vs_escalation(ax, df: pd.DataFrame, table: pd.DataFrame, meta: dict) -> None:
    for probe in PROBE_NAMES:
        sub = df[(df["strategy"] == "probe_cascade") & (df["probe"] == probe)]
        sub = sub.sort_values("frac_escalated")
        ax.plot(sub["frac_escalated"] * 100, sub["accuracy"],
                color=PROBE_COLORS[probe], marker=PROBE_MARKERS[probe],
                markersize=2.8, linewidth=1.6,
                label=f"{PROBE_PRETTY[probe]}")
    aq = float(table["qwen_sample0_correct"].mean())
    at = float(table["teacher_greedy_correct"].mean())
    ax.axhline(aq, color="#3182bd", linestyle="--", linewidth=0.8, alpha=0.5)
    ax.axhline(at, color="#000000", linestyle="--", linewidth=0.8, alpha=0.5)
    ax.text(2, aq + 0.005, f"Qwen alone: {aq:.3f}", fontsize=8, color="#3182bd")
    ax.text(2, at - 0.012, f"Teacher alone: {at:.3f}", fontsize=8)
    ax.set_xlabel("% escalated to teacher")
    ax.set_ylabel("Avg accuracy")
    ax.set_title(f"Accuracy vs escalation budget", fontsize=9.5)
    ax.set_xlim(0, 100)
    ax.set_ylim(min(aq, at) - 0.02, max(aq, at) + 0.04)
    ax.grid(linestyle=":", alpha=0.4)
    ax.legend(fontsize=8.0, loc="lower right")


def panel_routing_at_threshold(ax, table: pd.DataFrame, meta: dict,
                               probe: str = "DCP_mlp",
                               escalation_rate: float = 0.30) -> None:
    """Quadrant chart at a fixed escalation rate (percentile-based)."""
    score = table[f"score_{probe}"].to_numpy()
    threshold = float(np.quantile(score, escalation_rate))
    qc = table["qwen_sample0_correct"].to_numpy()
    confident = score > threshold
    correct = qc > 0.5
    quads = {
        "TT": int((confident & correct).sum()),
        "TF": int((confident & (~correct)).sum()),
        "FT": int(((~confident) & correct).sum()),
        "FF": int(((~confident) & (~correct)).sum()),
    }
    n = len(table)
    qwen_acc_when_committed = quads["TT"] / max(quads["TT"] + quads["TF"], 1)
    n_esc = (~confident).sum()
    teacher_corr_when_esc = ((~confident) & (table["teacher_greedy_correct"] > 0.5)).sum()
    teacher_acc_on_esc = teacher_corr_when_esc / max(n_esc, 1)

    cats = ["Conf+Corr\n(commit ✓)", "Conf+WRONG\n(commit ✗)",
            "Unsure+Corr\n(escalate, waste)", "Unsure+Wrong\n(escalate)"]
    counts = [quads["TT"], quads["TF"], quads["FT"], quads["FF"]]
    colors = ["#2ca02c", "#d62728", "#ff7f0e", "#7f7f7f"]
    ax.bar(range(4), counts, color=colors, alpha=0.85,
           edgecolor="black", linewidth=0.5)
    for i, c in enumerate(counts):
        ax.text(i, c + max(counts) * 0.02, f"{c}\n({c/n*100:.0f}%)",
                ha="center", fontsize=7.5)
    ax.set_xticks(range(4))
    ax.set_xticklabels(cats, fontsize=7.5)
    ax.set_ylabel("Question count")
    ax.set_title(f"Routing @ DCP escalation = {escalation_rate:.0%} (th={threshold:.3g})\n"
                 f"Qwen acc when commit: {qwen_acc_when_committed:.2%}  |  "
                 f"Teacher acc on escalated: {teacher_acc_on_esc:.2%}",
                 fontsize=9)
    ax.set_ylim(0, max(counts) * 1.30)
    ax.grid(axis="y", linestyle=":", alpha=0.4)


# ---------------------------------------------------------------------------
# Per-dataset and combined dashboards
# ---------------------------------------------------------------------------


def make_per_dataset_dashboard(dataset: str) -> tuple[pd.DataFrame, dict]:
    table, meta = build_aligned_table(dataset)
    cost_teacher = meta["cost_ratio_teacher_over_qwen"]
    df = sweep_all_strategies(table, cost_teacher)
    df.to_csv(THIS_DIR / "results" / f"cascade_2tier_{dataset}_results.csv", index=False)
    targets = [0.30, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65]
    savings = cost_savings_at_acc(df, targets, cost_teacher)
    savings.to_csv(THIS_DIR / "results" / f"cascade_2tier_{dataset}_savings.csv", index=False)
    print(f"\n=== {dataset} ===")
    print(f"  n={meta['n_aligned']}  qwen={meta['qwen_acc']:.3f}  "
          f"teacher={meta['teacher_acc']:.3f}  "
          f"teacher_lat_med={meta['teacher_latency_ms_median']:.0f}ms  "
          f"cost ratio={cost_teacher:.1f}")
    print(savings.to_string(index=False))

    fig = plt.figure(figsize=(20, 12))
    gs = GridSpec(2, 2, figure=fig, hspace=0.40, wspace=0.30,
                  left=0.06, right=0.97, top=0.92, bottom=0.06,
                  height_ratios=[1.2, 1.0])
    fig.suptitle(
        f"2-Tier Cascade — Qwen-7B → GPT-OSS-120B on {DATASET_PRETTY[dataset]}\n"
        f"n={meta['n_aligned']} aligned | real measured GPT-OSS latencies | "
        f"DCP-MLP / SEPs-LR / SEPs-Ridge routing",
        fontsize=13, fontweight="bold", y=0.985,
    )
    panel_pareto(fig.add_subplot(gs[0, :]), df, table, meta)
    panel_acc_vs_escalation(fig.add_subplot(gs[1, 0]), df, table, meta)
    panel_routing_at_threshold(fig.add_subplot(gs[1, 1]), table, meta,
                               probe="DCP_mlp", escalation_rate=0.30)
    out = THIS_DIR / "reports" / f"dashboard_cascade_2tier_{dataset}.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {out}")
    return df, meta


def make_combined_dashboard(per_ds: dict[str, pd.DataFrame],
                            metas: dict[str, dict]) -> None:
    fig = plt.figure(figsize=(20, 14))
    gs = GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.30,
                  left=0.05, right=0.98, top=0.94, bottom=0.05)
    fig.suptitle(
        "2-Tier Cascade Generalisation: TriviaQA (ID) → HotpotQA & NQ (OOD)\n"
        "Qwen2.5-7B (student) → GPT-OSS-120B (teacher), real measured latencies",
        fontsize=13, fontweight="bold", y=0.985,
    )

    # Need ID metas/df too — recompute from existing CSVs
    id_results = pd.read_csv(THIS_DIR / "results" / "cascade_2tier_results.csv")
    id_table = pd.read_csv(THIS_DIR / "results" / "qwen7b" /
                           "per_item_predictions_id_best.csv")
    # Build a meta_id ourselves
    aq = float(id_results[id_results["strategy"] == "always_qwen"]["accuracy"].iloc[0])
    at = float(id_results[id_results["strategy"] == "always_teacher"]["accuracy"].iloc[0])
    cr = float(id_results[id_results["strategy"] == "always_teacher"]["cost"].iloc[0])
    meta_id = {"dataset": "id", "n_aligned": 500,
               "qwen_acc": aq, "teacher_acc": at,
               "cost_ratio_teacher_over_qwen": cr,
               "teacher_latency_ms_median": cr * QWEN_LATENCY_MS}
    metas_full = {"id": meta_id, **metas}
    dfs_full = {"id": id_results, **per_ds}

    # We don't have an aligned id_table for routing panel; use a stub from
    # the per_item_predictions_id_best.csv (DCP_mlp & qwen sample0 correctness
    # come from y_true). y_true == qwen sample0 strict_correct.
    id_table_stub = id_table[id_table["probe"] == "DCP_mlp"][
        ["question_id", "y_true", "y_score"]
    ].rename(columns={"y_true": "qwen_sample0_correct",
                      "y_score": "score_DCP_mlp"})
    # We need teacher_greedy_correct on ID; load it from anchor if available
    anchor_dir = Path("/zhutingqi/song/Plan_gpt55/cross_model_anchor/runs/"
                      "run_20260513_012413_gptoss_anchor_triviaqa_full500_k4_tok256")
    teacher_id = {}
    with open(anchor_dir / "teacher_generations.jsonl") as f:
        for line in f:
            r = json.loads(line)
            if r.get("teacher_decode_mode") != "greedy":
                continue
            teacher_id[r["question_id"]] = r.get("teacher_strict_correct", 0)
    id_table_stub["teacher_greedy_correct"] = id_table_stub["question_id"].map(teacher_id).fillna(0)
    # Add SEPs scores for plotting compatibility (only DCP needed for routing panel)
    for p in ["SEPs_logreg", "SEPs_ridge"]:
        sub = id_table[id_table["probe"] == p][["question_id", "y_score"]].rename(
            columns={"y_score": f"score_{p}"})
        id_table_stub = id_table_stub.merge(sub, on="question_id", how="left")
    tables_full = {"id": id_table_stub}

    for col, ds in enumerate(["id", "hotpotqa", "nq"]):
        meta = metas_full[ds]
        df = dfs_full[ds]
        if ds in tables_full:
            tbl = tables_full[ds]
        else:
            tbl, _ = build_aligned_table(ds)
        panel_pareto(fig.add_subplot(gs[0, col]), df, tbl, meta)
        panel_acc_vs_escalation(fig.add_subplot(gs[1, col]), df, tbl, meta)
        panel_routing_at_threshold(fig.add_subplot(gs[2, col]), tbl, meta,
                                   probe="DCP_mlp", escalation_rate=0.30)

    out = THIS_DIR / "reports" / "dashboard_cascade_2tier_ood.png"
    fig.savefig(out, dpi=140, bbox_inches="tight")
    plt.close(fig)
    print(f"\n[combined] -> {out}")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--datasets", nargs="+", default=["hotpotqa", "nq"])
    args = p.parse_args()

    (THIS_DIR / "results").mkdir(exist_ok=True)
    (THIS_DIR / "reports").mkdir(exist_ok=True)

    per_ds: dict[str, pd.DataFrame] = {}
    metas: dict[str, dict] = {}
    summary_rows: list[dict] = []
    for ds in args.datasets:
        df, meta = make_per_dataset_dashboard(ds)
        per_ds[ds] = df
        metas[ds] = meta
        # Headline rows for combined summary
        for probe in PROBE_NAMES:
            sub = df[(df["strategy"] == "probe_cascade") & (df["probe"] == probe)]
            # Pareto: at fixed cost = cheapest meeting teacher_acc-2pp
            target_acc = meta["teacher_acc"] - 0.02
            meet = sub[sub["accuracy"] >= target_acc].sort_values("cost")
            if not meet.empty:
                r = meet.iloc[0]
                summary_rows.append({
                    "dataset": ds, "probe": probe,
                    "qwen_acc": meta["qwen_acc"],
                    "teacher_acc": meta["teacher_acc"],
                    "cost_ratio": meta["cost_ratio_teacher_over_qwen"],
                    "target_acc": target_acc,
                    "min_cost_to_target": float(r["cost"]),
                    "frac_escalated": float(r["frac_escalated"]),
                    "saving_vs_always_teacher_pct":
                        100 * (meta["cost_ratio_teacher_over_qwen"] - r["cost"]) /
                        meta["cost_ratio_teacher_over_qwen"],
                })

    pd.DataFrame(summary_rows).to_csv(
        THIS_DIR / "results" / "cascade_2tier_ood_summary.csv", index=False)

    make_combined_dashboard(per_ds, metas)

    print("\n=== SUMMARY ===")
    print(pd.DataFrame(summary_rows).to_string(index=False))


if __name__ == "__main__":
    main()
